MINI-TEAM3/mini3-server

build.gradle
src/main/java/com/fc/mini3server/_core/security/JwtAuthenticationFilter.java
src/main/java/com/fc/mini3server/_core/security/JwtTokenProvider.java
src/main/java/com/fc/mini3server/service/UserService.java

* 로그인 시 jwt token에 auth 분류 필터 추가 (USER or ADMIN)
* API 호출 시 auth를 기준으로 접근 제어

Hotfix/#22 로그인 API 변경 관련

---

src/main/java/com/fc/mini3server/repository/DeptRepository.java
src/main/java/com/fc/mini3server/service/DeptService.java

병원 아이디가 없는 경우 400에러 -> 200 으로 응답 후 빈 리스트 전달

병원 과 리스트 출력 API 리팩토링

---

src/main/java/com/fc/mini3server/_core/handler/MyExceptionHandler.java
src/main/java/com/fc/mini3server/_core/handler/exception/Exception400.java
src/main/java/com/fc/mini3server/_core/security/JwtAuthenticationFilter.java
src/main/java/com/fc/mini3server/_core/security/JwtTokenProvider.java
src/main/java/com/fc/mini3server/_core/security/SecurityConfig.java
src/main/java/com/fc/mini3server/controller/UserController.java
src/main/java/com/fc/mini3server/domain/User.java
src/main/java/com/fc/mini3server/dto/UserRequestDTO.java
src/main/java/com/fc/mini3server/service/UserService.java

* 비밀번호 변경 기능 추가
* 에러 핸들링 : Exception 400 생성자 추가, BadCredentialsException 핸들러 추가
* JWT 토큰 구조 변경 : Principal에 패스워드 클레임 추가

Feature/#20 비밀번호 변경 구현

---

src/main/java/com/fc/mini3server/_core/handler/MyExceptionHandler.java
src/main/java/com/fc/mini3server/dto/UserRequestDTO.java
src/main/java/com/fc/mini3server/service/UserService.java

* 회원가입 시 연차, 당직 각각 15, 3으로 초기화
* 회원가입 시 level 명시하지 않으면 INTERN으로 초기화 (내일 회의에서 논의 예정)
* UserService register 메서드 try - catch 처리
* Exception Handler 예외 처리 메서드 추가

Feature/#30 회원가입 데이터 초기화 관련 리팩토링

---

src/main/java/com/fc/mini3server/_core/handler/MyExceptionHandler.java

* 중복된 이메일로 회원가입 하는 상황을 핸들링 하기 위한 코드 추가

[Hotfix] 회원가입 이메일 UNIQUE 제약조건 에러 핸들링

---

src/main/java/com/fc/mini3server/controller/UserController.java
src/main/java/com/fc/mini3server/dto/UserRequestDTO.java
src/main/java/com/fc/mini3server/dto/UserResponseDTO.java
src/main/java/com/fc/mini3server/service/UserService.java

* 마이페이지 구현
* 마이페이지 수정 구현
* User ResponseDTO 필드 구조 변경

Feature/#21 마이페이지, 마이페이지 수정 구현

---

src/main/java/com/fc/mini3server/controller/UserController.java

* 로그인 메서드만 공통 Response 포맷에서 벗어나 있음
* 공통 응답 포맷에 맞춰 로그인 메서드 return 타입 리팩토링

[Hotfix] 유저 API 반환 타입 리팩토링

---

build.gradle
src/main/java/com/fc/mini3server/_core/config/WebMvcConfig.java
src/main/java/com/fc/mini3server/service/UserService.java
src/main/resources/application.yml

* 파일 저장 경로 변경
* 환경변수 추가 및 이미지 처리를 위한 config 파일 추가

[Fix] 파일 업로드 수정

---

src/main/resources/application.yml

[Fix] 이미지 파일 로드 실패 해결

---

src/main/java/com/fc/mini3server/controller/ScheduleController.java
src/main/java/com/fc/mini3server/domain/EvaluationEnum.java
src/main/java/com/fc/mini3server/dto/ScheduleRequestDTO.java
src/main/java/com/fc/mini3server/dto/ScheduleResponseDTO.java
src/main/java/com/fc/mini3server/repository/ScheduleRepository.java
src/main/java/com/fc/mini3server/service/ScheduleService.java
src/main/resources/application.yml

- schedule 클래스들의 충돌 해결
close #16

Feat #16: 연차,당직 관련 기능 구현

---

src/main/java/com/fc/mini3server/controller/UserController.java
src/main/java/com/fc/mini3server/dto/UserRequestDTO.java
src/main/java/com/fc/mini3server/dto/UserResponseDTO.java
src/main/java/com/fc/mini3server/service/UserService.java

* old_password -> oldPassword
* new_password -> newPassword
* emp_no -> empNo
* hospital_id -> hospitalId
* dept_id -> deptId
* profile_image_url -> profileImageUrl
* hiredate -> hireDate
* created_at -> createdAt
* updated_at -> updatedAt

유저 도메인 Request & Response 카멜케이스 통일

---

src/main/java/com/fc/mini3server/dto/UserRequestDTO.java
src/main/java/com/fc/mini3server/service/UserService.java

<p>회원가입 Request 필드 수정이 누락되어 수정 후 다시 PR 올립니다.</p>

유저 도메인 Request & Response 카멜케이스 통일 - 2

---

src/main/java/com/fc/mini3server/_core/handler/Message.java
src/main/java/com/fc/mini3server/service/UserService.java

* 유저 도메인 내 모든 예외 Messages 인터페이스로 통일

유저 도메인 에러 메시지 정렬

---

src/main/java/com/fc/mini3server/_core/config/SwaggerConfig.java
src/main/java/com/fc/mini3server/_core/utils/DBInit.java
src/main/java/com/fc/mini3server/dto/ScheduleResponseDTO.java
src/main/java/com/fc/mini3server/repository/ScheduleRepository.java
src/main/java/com/fc/mini3server/service/ScheduleService.java

- User의 병원 아이디 조회 하여 해당 병원에 있는 정보만 출력
- 응답 값 hospitalName 추가
- 스웨거 인증정보 넣을 수 있도록 수정

날짜별 연차/당직 조회 리팩토링

---

src/main/java/com/fc/mini3server/_core/handler/Message.java
src/main/java/com/fc/mini3server/controller/UserController.java
src/main/java/com/fc/mini3server/service/UserService.java

유저 도메인 로깅 작업

---

src/main/java/com/fc/mini3server/_core/handler/Message.java
src/main/java/com/fc/mini3server/controller/ScheduleController.java
src/main/java/com/fc/mini3server/domain/User.java
src/main/java/com/fc/mini3server/dto/ScheduleRequestDTO.java
src/main/java/com/fc/mini3server/repository/ScheduleRepository.java
src/main/java/com/fc/mini3server/service/ScheduleService.java

- 연차 등록 및 수정 시 중복된 일자는 신청이 안 되도록 예외처리
- 연차 삭제 시 차감된 연차일을 다시 복구
- 모든 스케줄이 삭제됐던 메서드를 연차만 삭제하도록 수정

Refactor #51: 예외처리

---

src/main/java/com/fc/mini3server/controller/UserController.java
src/main/java/com/fc/mini3server/dto/UserRequestDTO.java

* Validation 처리 메서드 생성 및 연동 완료
* 회원정보 수정 DTO 규칙 추가 및 연동 완료
* 유저 도메인 모든 리팩토링 종료

유저 도메인 Request & Response DTO 리팩토링

---

src/main/java/com/fc/mini3server/_core/utils/DBInit.java
src/main/java/com/fc/mini3server/controller/AdminController.java
src/main/java/com/fc/mini3server/dto/AdminResponseDTO.java
src/main/java/com/fc/mini3server/repository/ScheduleRepository.java
src/main/java/com/fc/mini3server/repository/UserRepository.java
src/main/java/com/fc/mini3server/service/AdminService.java

adminpage 리팩토링

---

src/main/java/com/fc/mini3server/controller/ScheduleController.java
src/main/java/com/fc/mini3server/domain/EvaluationEnum.java
src/main/java/com/fc/mini3server/service/AdminService.java

당직 변경 오류 수정

---

src/main/java/com/fc/mini3server/domain/User.java
src/main/java/com/fc/mini3server/service/AdminService.java

fix #80: 연차 반려 시 연차 횟수 다시 증가
